# Generated by Django 4.1.1 on 2022-09-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_shop_item_gallery_description_gallery_header_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallery_image',
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
    ]
