# Generated by Django 4.1.1 on 2022-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_gallery_gallery_image_alter_dish_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_image',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallery_image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
