# Generated by Django 4.1.1 on 2022-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_gallery_image_is_first_alter_gallery_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.CharField(blank=True, choices=[('GL', 'Gluten'), ('MLS', 'Molluscs')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
