# Generated by Django 4.1.1 on 2022-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_dish_allergens_dish_description_dish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='allergens',
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_celery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_crustaceans',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_eggs',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_fish',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_gluten',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_lupin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_milk',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_molluscs',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_mustard',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_peanuts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_sesame',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_soya',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_sulphites',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_tomato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='allergen_tree_nuts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
