# Generated by Django 4.1.1 on 2022-09-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_ingredients_alter_gallery_image_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
