# Generated by Django 4.1.1 on 2022-09-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_dish_delete_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
