# Generated by Django 4.1.1 on 2022-10-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_delete_wine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop_item',
        ),
    ]
