# Generated by Django 4.1.6 on 2023-02-13 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contacts_dish_wine_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'Menues'},
        ),
        migrations.AddField(
            model_name='menu',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
