# Generated by Django 4.1.6 on 2023-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_dish_options_alter_menu_options_menu_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
