# Generated by Django 4.1.6 on 2023-02-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_menu_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
