# Generated by Django 4.1.6 on 2023-02-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='in_cellar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
