# Generated by Django 4.1.6 on 2023-02-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_wine_in_cellar_wine_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='in_cellar',
            new_name='in_our_cellar',
        ),
    ]
