# Generated by Django 4.1.6 on 2023-02-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_dessert_description_alter_entree_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opening_hours',
            new_name='Opening_hour',
        ),
    ]
