# Generated by Django 4.1.6 on 2023-02-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_opening_hours_opening_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='in_our_cellar',
            new_name='bottles_in_our_cellar',
        ),
    ]
