# Generated by Django 4.1.6 on 2023-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_wine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dessert',
            field=models.ManyToManyField(blank=True, to='website.dessert'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='entree',
            field=models.ManyToManyField(blank=True, to='website.entree'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='first_dish',
            field=models.ManyToManyField(blank=True, to='website.first_dish'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='second_dish',
            field=models.ManyToManyField(blank=True, to='website.second_dish'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='side_dish',
            field=models.ManyToManyField(blank=True, to='website.side_dish'),
        ),
    ]
