# Generated by Django 4.1.6 on 2023-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_menu_dessert_alter_menu_entree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opening_hour',
            old_name='open',
            new_name='weekdays',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='opening_hour',
            name='closing_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opening_hour',
            name='weekend',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
