# Generated by Django 4.1.6 on 2023-02-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_open_opening_hour_weekdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening_hour',
            name='weekdays',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
