# Generated by Django 4.1.6 on 2023-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_business_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, default='Il Nostro Menù', max_length=100),
        ),
    ]
