# Generated by Django 4.1.1 on 2022-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0002_grocerylist_wine_rename_allergens_allergen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='grocery_list',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='grocer.ingredient'),
        ),
    ]
