# Generated by Django 4.1.1 on 2022-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0004_wine_grapes_wine_producer_wine_year_alter_wine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='month',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('RED', 'Red'), ('BUBBLES', 'Bubbles'), ('WHITE', 'White'), ('ROSE', 'Rose'), ('SWEET', 'Sweet')], default='RED', max_length=20),
        ),
    ]
