# Generated by Django 4.1.1 on 2022-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0006_remove_wine_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='is_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wine',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
