# Generated by Django 4.1.1 on 2022-10-01 11:13

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0007_wine_is_shown_wine_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
    ]
