# Generated by Django 4.1.1 on 2022-10-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0008_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
