# Generated by Django 4.1.1 on 2022-10-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0010_alter_wine_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='producer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
