# Generated by Django 4.1.1 on 2022-10-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0011_alter_wine_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocer.producer'),
        ),
    ]
