# Generated by Django 4.1.1 on 2022-10-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0012_alter_wine_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(blank=True, choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=6, null=True),
        ),
    ]
