# Generated by Django 4.1.1 on 2022-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0015_alter_dish_name_alter_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='cost_from_producer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='quantity_in_bottles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
