# Generated by Django 4.1.1 on 2022-10-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0016_wine_cost_from_producer_wine_quantity_in_bottles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='cost_from_producer',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='quantity_in_bottles',
        ),
    ]
