# Generated by Django 4.1.1 on 2022-10-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0018_alter_wine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['is_shown']},
        ),
    ]
