# Generated by Django 4.1.1 on 2022-10-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0020_alter_wine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['-is_shown', 'order']},
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='type',
            new_name='wine_type',
        ),
    ]
