# Generated by Django 4.1.1 on 2022-10-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0021_alter_wine_options_rename_type_wine_wine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
